### PR TITLE
Solution to the stefan problem

### PR DESCRIPTION
**Pull request by karthigeyanrgs**
I have added annotations for the code.

### CODE REVIEW

**Comment by agzimmerman** [comment]
Is this ready for me to review?

**Comment by karthigeyanrgs** [comment]
Yes it is.

**Comment by agzimmerman** [comment]
What have you done to verify whether or not the result is reasonable? 

Looking through the notebook, I see a few implementation errors, e.g. "T_t = (T )/Delta_t" must be wrong, and the definition of $phi(h)$ looks exactly like my definition of $phi(T)$ (whereas the two should be different). 

Also is $c$ in the definition of $T(h)$ really the specific heat capacity? How well does your $T(h)$ approximate the true temperature-dependent enthalpy? I think I've asked you before to plot this clearly and show that the curve has the right properties.

I don't think I should list any more issues/questions until you've shown something to verify your result.

**Comment by karthigeyanrgs** [comment]
I will work on it. Thanks for the feedback.

**Comment by karthigeyanrgs** [comment]
The problem has been resolved

**Pull request closed without merging**
